const initialData={pages:[{id:'home',name:'Home',boards:[{id:'work',name:'My Workspace',links:[['Gmail','https://mail.google.com'],['ChatGPT','https://chatgpt.com'],['Google Docs','https://docs.google.com']]},{id:'notes',name:'Notes & Docs',links:[['Notion','https://notion.so'],['Google Drive','https://drive.google.com'],['Obsidian','https://obsidian.md']]},{id:'comms',name:'Communication',links:[['Slack','https://slack.com'],['Discord','https://discord.com'],['WhatsApp','https://web.whatsapp.com']]},{id:'research',name:'Research',links:[['Google','https://google.com'],['YouTube','https://youtube.com'],['Wikipedia','https://wikipedia.org']]}]},{id:'work-page',name:'Work',boards:[]},{id:'learning',name:'Learning',boards:[]}]};
const defaultSettings={visibleCount:6,masterPassword:'',recoveryPassword:''};
let data,settings,activePage='home',privacy=false,incognito=false,modalMode='board',selectedBoardId,contextTarget=null,passwordEditing=false;const expanded=new Set();
const $=s=>document.querySelector(s),id=()=>crypto.randomUUID(),page=()=>data.pages.find(p=>p.id===activePage),esc=t=>{const d=document.createElement('div');d.textContent=t;return d.innerHTML},fav=url=>`https://www.google.com/s2/favicons?domain_url=${encodeURIComponent(url)}&sz=32`;
async function init(){const saved=await chrome.storage.local.get(['workspace','settings','ui']);data=saved.workspace||initialData;settings={...defaultSettings,...saved.settings};const ui=saved.ui||{};if(ui.activePage&&data.pages.some(p=>p.id===ui.activePage))activePage=ui.activePage;privacy=!!ui.privacy;incognito=!!ui.incognito;if(Array.isArray(ui.expanded))ui.expanded.forEach(k=>expanded.add(k));applySettings();$('#visibleCount').insertAdjacentHTML('beforeend','<option value="0">All</option>');for(let i=1;i<=15;i++)$('#visibleCount').insertAdjacentHTML('beforeend',`<option value="${i}">${i}</option>`);await mergeQuickSaves();render();$('#incognitoButton').style.color=incognito?'var(--green)':'';if(new URLSearchParams(location.search).get('panel')==='search')openSearch()}
async function save(){await chrome.storage.local.set({workspace:data})}
function saveUi(){chrome.storage.local.set({ui:{activePage,privacy,incognito,expanded:[...expanded]}})}
function applySettings(){document.body.classList.remove('light');document.body.style.backgroundImage='';document.body.style.backgroundSize='';document.body.style.backgroundAttachment=''}
function render(){
 $('#pageTabs').innerHTML=data.pages.map(p=>`<div class="page-tab ${p.id===activePage?'active':''}"><button class="tab-name" data-page="${p.id}">${esc(p.name)}</button></div>`).join('');
 $('#pageMenu').innerHTML=data.pages.map(p=>`<button class="page-menu-item ${p.id===activePage?'active':''}" data-page-menu="${p.id}" type="button">${esc(p.name)}</button>`).join('');
 const boards=page().boards;
 $('#boardGrid').innerHTML=boards.length?boards.map(b=>boardMarkup(b)).join(''):'<p class="empty">This page is ready for its first board. Create one with the + Board button.</p>';
 document.body.classList.toggle('privacy',privacy);bind()
}
function boardMarkup(b){const locked=!!b.locked,showAll=expanded.has(b.id),limit=showAll||settings.visibleCount===0?b.links.length:settings.visibleCount,links=b.links.slice(0,limit),canExpand=!locked&&settings.visibleCount>0&&b.links.length>settings.visibleCount;return `<article class="board ${locked?'locked':''}" draggable="${!locked}" data-board="${b.id}"><div class="board-head"><h3>${esc(b.name)}</h3><span class="board-count">${b.links.length} links</span><button class="board-lock ${locked?'locked':''}" data-lock-board="${b.id}" title="${locked?'Unlock':'Lock'} board">${locked?'&#128274;':'&#128275;'}</button></div>${locked?'<p class="lock-message">This board is locked. Unlock it to reveal links.</p>':''}<ul class="link-list">${links.map((l,i)=>linkMarkup(l,b.id,i)).join('')}</ul>${canExpand?`<button class="show-more" data-expand-board="${b.id}">${showAll&&!locked?'Show fewer links':'Show more links'}</button>`:''}<button class="add-link" data-add-link="${b.id}">+ Add link</button></article>`}
function closePageMenu(){const menu=$('#pageMenu'),button=$('#pageMenuButton');menu.hidden=true;button.setAttribute('aria-expanded','false')}
function closeActionsMenu(){const menu=$('#headerActions'),button=$('#actionsMenuButton');menu.classList.remove('open');button.setAttribute('aria-expanded','false')}
function linkMarkup(l,boardId,i){return `<li class="bookmark" draggable="true" data-link="${i}" data-board="${boardId}"><img class="favicon" src="${fav(l[1])}" alt="" /><a class="bookmark-title" href="${esc(l[1])}">${esc(l[0])}</a><button class="open-private" data-private="${esc(l[1])}" title="Open privately">&#8599;</button></li>`}
function bind(){
 document.querySelectorAll('.tab-name').forEach(b=>{b.onclick=()=>{activePage=b.dataset.page;saveUi();render()}});
 document.querySelectorAll('[data-page-menu]').forEach(b=>{b.onclick=()=>{activePage=b.dataset.pageMenu;saveUi();closePageMenu();render()}});
 document.querySelectorAll('[data-expand-board]').forEach(b=>b.onclick=()=>{const board=page().boards.find(x=>x.id===b.dataset.expandBoard);if(board?.locked)return toast('Unlock this board to view its links');const key=b.dataset.expandBoard;expanded.has(key)?expanded.delete(key):expanded.add(key);saveUi();render()});
 document.querySelectorAll('[data-lock-board]').forEach(b=>b.onclick=async()=>{const board=page().boards.find(x=>x.id===b.dataset.lockBoard);if(board.locked){const pass=prompt('Enter the master password (or recovery password)');if(![settings.masterPassword,settings.recoveryPassword].filter(Boolean).includes(pass))return toast('Incorrect password');delete board.locked;delete board.password;await save();render();toast('Board unlocked')}else{if(!settings.masterPassword)return toast('Set a master password in Settings first');board.locked=true;await save();render();toast('Board locked')}});
 document.querySelectorAll('[data-add-link]').forEach(b=>b.onclick=()=>openModal('link',b.dataset.addLink));document.querySelectorAll('.bookmark-title').forEach(a=>a.onclick=e=>{if(incognito){e.preventDefault();chrome.windows.create({url:a.href,incognito:true})}});document.querySelectorAll('[data-private]').forEach(b=>b.onclick=()=>chrome.windows.create({url:b.dataset.private,incognito:true}));
 let dragged;document.querySelectorAll('.board').forEach(el=>{el.ondragstart=e=>{dragged={kind:'board',board:el.dataset.board};el.classList.add('dragging');e.dataTransfer.effectAllowed='move'};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>e.preventDefault();el.ondrop=async e=>{e.preventDefault();if(dragged?.kind!=='board'||dragged.board===el.dataset.board)return;const a=page().boards,from=a.findIndex(x=>x.id===dragged.board),to=a.findIndex(x=>x.id===el.dataset.board);a.splice(to,0,a.splice(from,1)[0]);await save();render()}});
 document.querySelectorAll('.bookmark').forEach(el=>{el.ondragstart=e=>{e.stopPropagation();dragged={kind:'link',board:el.dataset.board,index:+el.dataset.link};el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>e.preventDefault();el.ondrop=async e=>{e.preventDefault();e.stopPropagation();if(dragged?.kind!=='link')return;const source=page().boards.find(b=>b.id===dragged.board),target=page().boards.find(b=>b.id===el.dataset.board),item=source.links.splice(dragged.index,1)[0];let at=+el.dataset.link;if(source===target&&dragged.index<at)at--;target.links.splice(at,0,item);await save();render()}})
}
function showContext(event,target){event.preventDefault();contextTarget=target;const menu=$('#contextMenu');menu.hidden=false;menu.style.left=`${Math.min(event.clientX,innerWidth-155)}px`;menu.style.top=`${Math.min(event.clientY,innerHeight-85)}px`}
function targetName(target){if(target.type==='page')return data.pages.find(p=>p.id===target.pageId)?.name;const board=page().boards.find(b=>b.id===target.boardId);return target.type==='board'?board?.name:board?.links[target.index]?.[0]}
async function renameTarget(){if(!contextTarget)return;const current=targetName(contextTarget),name=prompt('New name',current||'');if(!name?.trim())return;const clean=name.trim();if(contextTarget.type==='page'){if(data.pages.some(p=>p.id!==contextTarget.pageId&&p.name.toLowerCase()===clean.toLowerCase()))return toast('A page with this name already exists');data.pages.find(p=>p.id===contextTarget.pageId).name=clean}else{const board=page().boards.find(b=>b.id===contextTarget.boardId);if(contextTarget.type==='board'){if(page().boards.some(b=>b.id!==board.id&&b.name.toLowerCase()===clean.toLowerCase()))return toast('A board with this name already exists');board.name=clean}else board.links[contextTarget.index][0]=clean}await save();render()}
async function deleteTarget(){if(!contextTarget)return;const t=contextTarget;if(t.type==='page'){if(data.pages.length===1)return toast('Keep at least one page');const index=data.pages.findIndex(p=>p.id===t.pageId),removed=data.pages.splice(index,1)[0];if(activePage===t.pageId)activePage=data.pages[0].id;saveUi();await save();render();toast('Page deleted',async()=>{data.pages.splice(index,0,removed);await save();render()})}else if(t.type==='board'){const boards=page().boards,index=boards.findIndex(b=>b.id===t.boardId),removed=boards.splice(index,1)[0];await save();render();toast('Board deleted',async()=>{boards.splice(index,0,removed);await save();render()})}else{const board=page().boards.find(b=>b.id===t.boardId),removed=board.links.splice(t.index,1)[0];await save();render();toast('Link deleted',async()=>{board.links.splice(t.index,0,removed);await save();render()})}}
$('#contextMenu').addEventListener('click',async e=>{const action=e.target.dataset.action;if(!action)return;$('#contextMenu').hidden=true;if(action==='rename')await renameTarget();if(action==='delete')await deleteTarget()});document.addEventListener('click',e=>{if(!$('#contextMenu').contains(e.target))$('#contextMenu').hidden=true;if(!e.target.closest('.page-menu-wrap'))closePageMenu();if(!e.target.closest('.actions-wrap')||e.target.closest('.header-actions button'))closeActionsMenu()});
document.addEventListener('contextmenu',e=>{const link=e.target.closest('.bookmark'),board=e.target.closest('.board'),tab=e.target.closest('.tab-name');if(!link&&!board&&!tab)return;e.preventDefault();if(link)return showContext(e,{type:'link',boardId:link.dataset.board,index:+link.dataset.link});if(board)return showContext(e,{type:'board',boardId:board.dataset.board});showContext(e,{type:'page',pageId:tab.dataset.page})},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#contextMenu').hidden=true;closePageMenu();closeActionsMenu()}});window.addEventListener('scroll',()=>{$('#contextMenu').hidden=true;closePageMenu();closeActionsMenu()},true);
function openModal(mode,boardId){modalMode=mode;selectedBoardId=boardId;$('#modalEyebrow').textContent=mode==='board'?'NEW BOARD':'NEW LINK';$('#modalTitle').textContent=mode==='board'?'Create a board':'Save a link';$('#urlField').hidden=mode==='board';$('#nameInput').value='';$('#urlInput').value='';$('#modal').showModal();$('#nameInput').focus()}
function normalUrl(value){let url=value.trim();if(!/^https?:\/\//i.test(url))url=`https://${url}`;try{return new URL(url).href}catch{return null}}
$('.close').onclick=()=>$('#modal').close();$('#cancelButton').onclick=()=>$('#modal').close();
$('#modalForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('#nameInput').value.trim();let url=$('#urlInput').value.trim();if(!name)return;if(modalMode==='board'){if(page().boards.some(b=>b.name.toLowerCase()===name.toLowerCase()))return toast('A board with this name already exists');page().boards.push({id:id(),name,links:[]})}else{url=normalUrl(url);if(!url){toast('Enter a valid website address');return}page().boards.find(b=>b.id===selectedBoardId).links.push([name,url])}await save();$('#modal').close();render()});
$('#addBoardButton').onclick=()=>openModal('board');$('#addPageButton').onclick=()=>{if(data.pages.length>=5)return toast('You can create up to 5 pages');const name=prompt('Name your new page');if(!name?.trim())return;const clean=name.trim();if(data.pages.some(p=>p.name.toLowerCase()===clean.toLowerCase()))return toast('A page with this name already exists');data.pages.push({id:id(),name:clean,boards:[]});activePage=data.pages.at(-1).id;saveUi();save();render()};
$('#pageMenuButton').onclick=e=>{e.stopPropagation();const menu=$('#pageMenu'),open=menu.hidden;menu.hidden=!open;$('#pageMenuButton').setAttribute('aria-expanded',String(open))};
$('#actionsMenuButton').onclick=e=>{e.stopPropagation();const open=$('#headerActions').classList.toggle('open');$('#actionsMenuButton').setAttribute('aria-expanded',String(open))};
$('#privacyButton').onclick=()=>{privacy=!privacy;saveUi();render();toast(privacy?'Privacy mode is on':'Privacy mode is off')};$('#incognitoButton').onclick=()=>{incognito=!incognito;saveUi();$('#incognitoButton').style.color=incognito?'var(--green)':'';toast(incognito?'Links will open privately':'Standard link opening restored')};
$('#importButton').onclick=async()=>{const tree=await chrome.bookmarks.getTree(),links=[];const visit=n=>{if(n.url)links.push([n.title||n.url,n.url]);n.children?.forEach(visit)};tree.forEach(visit);page().boards.push({id:id(),name:'Imported bookmarks',links:links.slice(0,100)});await save();render();toast(`${links.length} Chrome bookmarks imported`)};
function openSearch(){const panel=$('#searchPanel');panel.hidden=false;$('#searchInput').value='';$('#searchResults').innerHTML='';$('#searchInput').focus()}function search(q){const hits=data.pages.flatMap(p=>p.boards.filter(b=>!b.locked).flatMap(b=>b.links.filter(l=>`${l[0]} ${l[1]}`.toLowerCase().includes(q.toLowerCase())).map(l=>({p,b,l}))));$('#searchResults').innerHTML=hits.length?hits.map(x=>`<a class="result" href="${esc(x.l[1])}"><img class="favicon" src="${fav(x.l[1])}" alt="" /><span>${esc(x.l[0])}<small>${esc(x.p.name)} / ${esc(x.b.name)}</small></span></a>`).join(''):`<p class="lock-message">${q?'No unlocked bookmarks found.':'Type to search your unlocked bookmarks.'}</p>`}
$('#searchButton').onclick=openSearch;$('#closeSearch').onclick=()=>$('#searchPanel').hidden=true;$('#searchInput').oninput=e=>search(e.target.value);$('#searchPanel').onclick=e=>{if(e.target===$('#searchPanel'))$('#searchPanel').hidden=true};
function showPasswordSetup(){passwordEditing=true;$('#passwordSetup').hidden=false;$('#passwordActions').hidden=true;$('#masterPassword').value='';$('#recoveryPassword').value='';$('#masterPassword').focus()}
async function renderCommands(){const list=$('#commandsList');if(!list||!chrome.commands?.getAll)return;const cmds=await chrome.commands.getAll();list.innerHTML=cmds.filter(c=>c.description).map(c=>`<li class="command-row"><span class="command-name">${esc(c.description)}</span><kbd class="command-key ${c.shortcut?'':'unset'}">${c.shortcut?esc(c.shortcut):'Not set'}</kbd></li>`).join('')}
$('#customizeCommands').onclick=()=>chrome.tabs.create({url:'chrome://extensions/shortcuts'});
$('#settingsButton').onclick=()=>{renderCommands();$('#visibleCount').value=settings.visibleCount;$('#passwordStatus').textContent=settings.masterPassword?'Password set':'Not set';passwordEditing=!settings.masterPassword;$('#passwordSetup').hidden=!!settings.masterPassword;$('#passwordActions').hidden=!settings.masterPassword;$('#masterPassword').value='';$('#recoveryPassword').value='';$('#settingsModal').showModal()};$('#closeSettings').onclick=()=>$('#settingsModal').close();
$('#changePassword').onclick=()=>{if(prompt('Enter your current master password')!==settings.masterPassword)return toast('Incorrect master password');showPasswordSetup()};
$('#forgotPassword').onclick=()=>{if(!settings.recoveryPassword)return toast('No recovery password was set');if(prompt('Enter your recovery password')!==settings.recoveryPassword)return toast('Incorrect recovery password');showPasswordSetup()};
$('#removePassword').onclick=async()=>{if(prompt('Enter your master password to remove it')!==settings.masterPassword)return toast('Incorrect master password');settings={...settings,masterPassword:'',recoveryPassword:''};data.pages.forEach(p=>p.boards.forEach(b=>{delete b.locked;delete b.password}));await chrome.storage.local.set({settings});await save();$('#passwordStatus').textContent='Not set';$('#passwordSetup').hidden=false;$('#passwordActions').hidden=true;passwordEditing=true;$('#masterPassword').value='';$('#recoveryPassword').value='';render();toast('Password removed and boards unlocked')};
$('#settingsModal form').addEventListener('submit',async e=>{e.preventDefault();let master=settings.masterPassword,recovery=settings.recoveryPassword;if(passwordEditing){const m=$('#masterPassword').value.trim(),r=$('#recoveryPassword').value.trim();if(m||r){if(!/^\d{6}$/.test(m)||!/^\d{6}$/.test(r))return toast('Both passwords must be exactly 6 digits');if(m===r)return toast('Use a different recovery password')}master=m;recovery=r}settings={...settings,visibleCount:+$('#visibleCount').value,masterPassword:master,recoveryPassword:recovery};await chrome.storage.local.set({settings});applySettings();$('#settingsModal').close();render();toast('Settings saved')});
async function mergeQuickSaves(){const {quickSaves=[]}=await chrome.storage.local.get('quickSaves');if(!quickSaves.length)return;const p=data.pages[0];let b=p.boards.find(b=>b.id==='quick-saves');if(!b){b={id:'quick-saves',name:'Quick Saves',links:[]};p.boards.unshift(b)}quickSaves.forEach(s=>{if(!b.links.some(l=>l[1]===s.url))b.links.push([s.title,s.url])});await chrome.storage.local.set({quickSaves:[]});await save()}
let toastTimer,toastHideTimer;
function hideToast(){const el=$('#toast');el.classList.remove('show');clearTimeout(toastHideTimer);toastHideTimer=setTimeout(()=>{try{el.hidePopover()}catch{}},340)}
function toast(msg,undo){const el=$('#toast');clearTimeout(toastTimer);clearTimeout(toastHideTimer);el.innerHTML='';const text=document.createElement('span');text.className='toast-text';text.textContent=msg;el.appendChild(text);if(undo){const button=document.createElement('button');button.className='toast-action';button.textContent='UNDO';button.onclick=async()=>{clearTimeout(toastTimer);await undo();hideToast();toast('Restored')};el.appendChild(button);const bar=document.createElement('span');bar.className='toast-bar';el.appendChild(bar)}if(!el.matches(':popover-open')){try{el.showPopover()}catch{}}void el.offsetWidth;el.classList.add('show');toastTimer=setTimeout(hideToast,undo?6000:3200)}init();
